### ISSUE TITLE
The Players - incorrect tournament articles returned

### ISSUE THREAD

**Issue by ezaleski2** [hlxsites/pga-tour-issues#22]
Hi David and Katie,

We're seeing an issue on the following pages: 
https://www.theplayers.com/ 
https://www.theplayers.com/news 

Both are returning articles from WGC Dell, not The Players.

I can see the following is being called on the page, which has a few references to r470 (wgc dell):

https://little-forest-58aa.david8603.workers.dev/?url=https%3A%2F%2Fwww.pgatour.com%2Fbin%2Fdata%2Ffeeds%2Fcontent.json%2Fpath%3D%2Fcontent%26tags%3DPGATOUR%3ATournaments%2F2017%2Fr470%2BPGATOUR%3ATournaments%2F2016%2Fr470%2BPGATOUR%3ATournaments%2F2018%2Fr470%2BPGATOUR%3ATournaments%2F2019%2Fr470%2BPGATOUR%3ATournaments%2F2020%2Fr470%2BPGATOUR%3ATournaments%2F2021%2Fr470%2BPGATOUR%3ATournaments%2F2022%2Fr470%2BPGATOUR%3ATournaments%2F2023%2Fr47%26size%3D100 

There's also an incomplete reference to dell at the end of the url, which is causing an error:
"Tag (PGATOUR:Tournaments/2023/r47) can not be resolved",

**Comment by davidnuescheler** [comment]
i think this was a regression that was addressed, let me know if we are good to close this issue.

**Comment by ezaleski2** [comment]
Sean addressed this issue and updated the team via slack , we can close
