### ISSUE TITLE
FedEx Teetimes and Field pages

### ISSUE THREAD

**Issue by ezaleski2** [hlxsites/pga-tour-issues#27]
Hello Franklin team,

Gary has added the two following pages to FedExChampionship dot com

https://www.fedexchampionship.com/tee-times

https://www.fedexchampionship.com/field

Opening this ticket to for assistance in getting the feed for both of these pages set up. 

Thank you,
Ed

**Comment by shsteimer** [comment]
@ezaleski2 

We have examples of the field and tee-time blocks in the block inventory at https://main--theplayers--hlxsites.hlx.page/drafts/uncled/block-inventory
Sharepoint doc link: https://adobe.sharepoint.com/:w:/r/sites/HelixProjects/_layouts/15/Doc.aspx?sourcedoc=%7B3DCA0821-E21F-4AFE-94E6-6EA820D45D96%7D&file=block-inventory.docx&action=default&mobileredirect=true

**Comment by shsteimer** [comment]
@ezaleski2 closing based on our call yesterday, if any ongoing issues or concerns, feel free to re-open.
