### ISSUE TITLE
Live Chat on Franklin Sites

### ISSUE THREAD

**Issue by ezaleski2** [hlxsites/pga-tour-issues#28]
Hi team,

We received the following request from the ticket sales team to include a 'live chat' feature on a handful of pages. We used to accomplish this with Raw Content modules when the pages lived in AEM. I found a conversation in slack from a few months ago that advised against raw content (/the franklin equivalent), so opening up this ticket. 

**THE PLAYERS**
https://www.theplayers.com/tickets
https://www.theplayers.com/hospitality

_Embed Code_
<script src="//sdk.engage.co/sdk.js"

               data-company="940C7DA7-86CB-CD21-8A84-E3658B0555BF"

               data-widget="the-players-widget"></script>
__ 

**Dell Technologies Match Play**
https://www.dellmatchplay.com/tickets

_Embed Code_

<script src="//sdk.engage.co/sdk.js"

               data-company="940C7DA7-86CB-CD21-8A84-E3658B0555BF"

               data-widget="dell-match-play"></script>
__ 

**Sentry Tournament of Champions**
https://www.sentrytournamentofchampions.com/tickets
https://www.sentrytournamentofchampions.com/hospitality

_Embed Code_
 
<script src="//sdk.engage.co/sdk.js"

               data-company="940C7DA7-86CB-CD21-8A84-E3658B0555BF"

               data-widget="sentry-tournament-of-champions"></script>

**Comment by shsteimer** [comment]
Hi @ezaleski2 

will take a look at this, believe it will require a small enhancement to our embed block to work properly.
