### ISSUE TITLE
Buttons in hero not displaying on mobile web

### ISSUE THREAD

**Issue by PatrickReganPGATOUR** [hlxsites/pga-tour-issues#4]
Issue: In the hero image, the buttons that display at the desktop breakpoint are not displaying on the mobile website breakpoint.

WRONG - Helix pages
https://main--theplayers--hlxsites.hlx.page/hospitality
https://main--theplayers--hlxsites.hlx.page/charity

vs. 

CORRECT - live theplayers.com pages
https://www.theplayers.com/hospitality.html
https://www.theplayers.com/charity.html

I'm sure there are more pages for examples, but if it's corrected here for these two, then my surmise is that this will resolve it moving forward for any other pages using this template.

**Comment by PatrickReganPGATOUR** [comment]
![helix-theplayers-hero-buttons-mobile-web](https://user-images.githubusercontent.com/111608743/185698866-4aa663da-cbfb-4bef-8092-542708f4bc6f.png)

**Comment by fkakatie** [comment]
resolved with: https://github.com/hlxsites/theplayers/commit/48863f2d393bf0c1644ff0c265c3936f57dc76bd

see: 
* https://main--theplayers--hlxsites.hlx.page/hospitality
* https://main--theplayers--hlxsites.hlx.page/charity
